// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2017-07-27 01:32:18.359465185 +0200 CEST
// using data from
// https://www.iana.org/assignments/ipv6-unicast-address-assignments/ipv6-unicast-address-assignments.xml
package ripego

func initIPv6(){
	addIPv6Prefix("2001:0000::/23", "whois.iana.org")
	addIPv6Prefix("2001:0200::/23", "whois.apnic.net")
	addIPv6Prefix("2001:0400::/23", "whois.arin.net")
	addIPv6Prefix("2001:0600::/23", "whois.ripe.net")
	addIPv6Prefix("2001:0800::/23", "whois.ripe.net")
	addIPv6Prefix("2001:0a00::/23", "whois.ripe.net")
	addIPv6Prefix("2001:0c00::/23", "whois.apnic.net")
	addIPv6Prefix("2001:0e00::/23", "whois.apnic.net")
	addIPv6Prefix("2001:1200::/23", "whois.lacnic.net")
	addIPv6Prefix("2001:1400::/23", "whois.ripe.net")
	addIPv6Prefix("2001:1600::/23", "whois.ripe.net")
	addIPv6Prefix("2001:1800::/23", "whois.arin.net")
	addIPv6Prefix("2001:1a00::/23", "whois.ripe.net")
	addIPv6Prefix("2001:1c00::/22", "whois.ripe.net")
	addIPv6Prefix("2001:2000::/20", "whois.ripe.net")
	addIPv6Prefix("2001:3000::/21", "whois.ripe.net")
	addIPv6Prefix("2001:3800::/22", "whois.ripe.net")
	addIPv6Prefix("2001:4000::/23", "whois.ripe.net")
	addIPv6Prefix("2001:4200::/23", "whois.afrinic.net")
	addIPv6Prefix("2001:4400::/23", "whois.apnic.net")
	addIPv6Prefix("2001:4600::/23", "whois.ripe.net")
	addIPv6Prefix("2001:4800::/23", "whois.arin.net")
	addIPv6Prefix("2001:4a00::/23", "whois.ripe.net")
	addIPv6Prefix("2001:4c00::/23", "whois.ripe.net")
	addIPv6Prefix("2001:5000::/20", "whois.ripe.net")
	addIPv6Prefix("2001:8000::/19", "whois.apnic.net")
	addIPv6Prefix("2001:a000::/20", "whois.apnic.net")
	addIPv6Prefix("2001:b000::/20", "whois.apnic.net")
	addIPv6Prefix("2003:0000::/18", "whois.ripe.net")
	addIPv6Prefix("2400:0000::/12", "whois.apnic.net")
	addIPv6Prefix("2600:0000::/12", "whois.arin.net")
	addIPv6Prefix("2610:0000::/23", "whois.arin.net")
	addIPv6Prefix("2620:0000::/23", "whois.arin.net")
	addIPv6Prefix("2800:0000::/12", "whois.lacnic.net")
	addIPv6Prefix("2a00:0000::/12", "whois.ripe.net")
	addIPv6Prefix("2c00:0000::/12", "whois.afrinic.net")
}
